apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

configMapGenerator:
- name: nginx-conf
  files:
  - nginx.conf

patchesStrategicMerge:
- deployment-add-secret.yaml
- service-add-NP.yaml
