apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app.kubernetes.io/name: guestbook
    helm.sh/chart: guestbook-0.2.0
    app.kubernetes.io/instance: guestbook
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/instance: guestbook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/instance: guestbook
    spec:
      containers:
      - name: guestbook
        image: "resouer/guestbook:v1"
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
